#pragma once

/**
 * RickAndMorty Mock - Configuration - Default values
 */

#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_NAME TEXT("%mock_name%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_STATUS TEXT("%mock_status%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_SPECIES TEXT("%mock_species%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_TYPE TEXT("%mock_type%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_GENDER TEXT("%mock_gender%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_ORIGIN TEXT("%mock_origin%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_LOCATION TEXT("%mock_location%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_IMAGE TEXT("%mock_image%")
#define RICKANDMORTYMOCKPLUGIN_CONFIGURATION_DEFAULT_COUNT 1
